# Generated by Django 3.0.5 on 2020-04-11 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200410_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999, message='Numer telefonu moze miec maksymalnie 9 cyfr!')]),
        ),
    ]
