# Generated by Django 3.0.5 on 2020-04-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='book.Person'),
        ),
    ]
